/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinenJNI */

#ifndef _Included_LinenJNI
#define _Included_LinenJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LinenJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LinenJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
